openapi: 3.1.0
info:
  title: Evo33 Logic Engine
  description: API for symbolic logic evaluation, contradiction detection, logic tracing, quantum-inspired logic modes, translating Boolean expressions, Codex Bridge functionality, Inference Engine functionality, Provenance engine queries and Trust transfer operations.
  version: "1.0.0"
servers:
  - url: https://evo33-gpt-api.onrender.com
paths:
  /solve:
    get:
      summary: Solve logic expressions
      operationId: solveLogicExpressions
      responses:
        '200':
          description: Logic solution

  /solve-legacy:
    get:
      summary: Solve legacy logic expressions
      operationId: solveLegacyExpressions
      responses:
        '200':
          description: Legacy logic solution

  /quantum:
    get:
      summary: Quantum-inspired logic solving
      operationId: quantumLogicSolving
      responses:
        '200':
          description: Quantum logic solution

  /scroll:
    get:
      summary: Codex reasoning scroll feature
      operationId: codexReasoningScroll
      responses:
        '200':
          description: Scroll results

  /schema:
    get:
      summary: Explore API schema
      operationId: exploreApiSchema
      responses:
        '200':
          description: API schema exploration details

  /explain:
    get:
      summary: Explanation of logic evaluation
      operationId: explainLogicEvaluation
      responses:
        '200':
          description: Logic explanation details

  /trace:
    get:
      summary: Trace logic evaluations step-by-step
      operationId: traceLogicEvaluations
      responses:
        '200':
          description: Logic evaluation trace

  /debug:
    get:
      summary: Debugging logical rules and conditions
      operationId: debugLogicalRules
      responses:
        '200':
          description: Debugging output details

  /translate:
    get:
      summary: Translate Boolean logic to natural language
      operationId: translateBooleanLogic
      responses:
        '200':
          description: Translated logic descriptions

  /codex-bridge:
  get:
    summary: Codex Bridge functionality
    operationId: codexBridge
    responses:
      '200':
        description: Codex Bridge Response

  /inference-engine:
  get:
    summary: Inference Engine functionality
    operationId: inferenceEngine
    responses:
      '200':
        description: Inference Engine Response

  get:
    summary: Inference engine operations
    operationId: inferenceEngine
    responses:
      '200':
        description: Inference Engine Response

  /provenance-engine:
  get:
    summary: Provenance engine queries
    operationId: provenanceEngine
    responses:
      '200':
        description: Provenance Engine Response

  /trust-transfer:
  get:
    summary: Trust transfer operations
    operationId: trustTransfer
    responses:
      '200':
        description: Trust Transfer Response
        
